<?php

return [
    'demo_otp' => env('BRIGHT_LEMON_DEMO_OTP', '123456'),

    'default_branch' => env('BRIGHT_LEMON_DEFAULT_BRANCH', 'Branch drop-off pending'),

    'ems' => [
        'enabled' => filter_var(env('BRIGHT_LEMON_EMS_ENABLED', false), FILTER_VALIDATE_BOOL),
        'mode' => env('ISRAEL_POST_SDK_MODE', 'test'),
        'api_url' => env('ISRAEL_POST_SDK_API_URL') ?: (env('ISRAEL_POST_SDK_MODE', 'test') === 'live'
            ? 'https://apimftprd.israelpost.co.il'
            : 'https://apimfttst.israelpost.co.il'),
        'subscription_key' => env('ISRAEL_POST_SDK_AUTH_INTERNATIONAL_SUBSCRIPTION_KEY_METHODS')
            ?: env('ISRAEL_POST_SDK_AUTH_SEND_PARCEL_INFO_API_OCP_APIM_SUBSCRIPTION_KEY')
            ?: env('ISRAEL_POST_SDK_AUTH_OCP_APIM_SUBSCRIPTION_KEY'),
        'username' => env('ISRAEL_POST_SDK_AUTH_USERNAME'),
        'password' => env('ISRAEL_POST_SDK_AUTH_PASSWORD'),
        'partner_code' => env('ISRAEL_POST_SDK_SETTINGS_INTL_PARTNER_CODE', '400327'),
        'delivery_type_code' => env('ISRAEL_POST_SDK_INTERNATIONAL_SHIPMENT_SETTINGS_DELIVERY_TYPE_CODE', 10),
        'shipment_type' => env('ISRAEL_POST_SDK_INTERNATIONAL_SHIPMENT_SETTINGS_SHIPMENT_TYPE', '10'),
        'currency' => env('BRIGHT_LEMON_EMS_CURRENCY', 'USD'),
        'rate_api_url' => env('BRIGHT_LEMON_EMS_RATE_API_URL'),
        'rate_carrier' => env('BRIGHT_LEMON_EMS_RATE_CARRIER', 'israel_post'),
        // Israel Post — particularly the test gateway (apimfttst.israelpost.co.il)
        // — regularly takes 60-90s to respond on SendParcelInfo/GetToken. The old
        // 30s default surfaced as `cURL error 28: Operation timed out` and the
        // admin's "record payment" action failed mid-flight, leaving the
        // shipment paid but without a label. 120s matches what we ship in the
        // main Shipper b2c-api SDK.
        'timeout' => env('BRIGHT_LEMON_EMS_TIMEOUT', 120),
        'default_recipient_postal_code' => env('BRIGHT_LEMON_EMS_DEFAULT_RECIPIENT_POSTAL_CODE', '00000'),
        'default_parcel' => [
            'length_cm' => env('BRIGHT_LEMON_EMS_DEFAULT_PARCEL_LENGTH_CM', 10),
            'width_cm' => env('BRIGHT_LEMON_EMS_DEFAULT_PARCEL_WIDTH_CM', 10),
            'height_cm' => env('BRIGHT_LEMON_EMS_DEFAULT_PARCEL_HEIGHT_CM', 10),
        ],
        'allowed_warning_codes' => array_filter(array_map(
            'trim',
            explode(',', env('BRIGHT_LEMON_EMS_ALLOWED_WARNING_CODES', '201'))
        )),
        'sender' => [
            'country_code' => env('BRIGHT_LEMON_EMS_SENDER_COUNTRY_CODE', 'IL'),
            // Used as a fallback when the customer leaves their email blank on
            // the public form. Israel Post's EMS validator rejects the parcel
            // with "10: Validation failed:SenderEmail is required" otherwise.
            'fallback_email' => env('BRIGHT_LEMON_EMS_SENDER_FALLBACK_EMAIL', 'support@iqdesk.xyz'),
        ],
        // Israel Post requires an HS (Harmonized System) tariff code on every
        // ParcelContent line. The public form doesn't ask for one — we map the
        // customer's package_type to a sensible 6-digit code. Tweak the `by_type`
        // entries if a more accurate code is needed for a specific category.
        'hs_codes' => [
            'default' => env('BRIGHT_LEMON_EMS_DEFAULT_HS_CODE', '999900'),
            'by_type' => [
                'Gift'           => env('BRIGHT_LEMON_EMS_HS_CODE_GIFT', '950300'),         // toys/games
                'Merchandise'    => env('BRIGHT_LEMON_EMS_HS_CODE_MERCHANDISE', '999900'),  // unspecified merchandise
                'Returned Goods' => env('BRIGHT_LEMON_EMS_HS_CODE_RETURNED', '999900'),
                'Documents'      => env('BRIGHT_LEMON_EMS_HS_CODE_DOCUMENTS', '490110'),    // printed matter
            ],
        ],
        'country_codes' => [
            'UNITED STATES' => 'US',
            'USA' => 'US',
            'UNITED KINGDOM' => 'GB',
            'GREAT BRITAIN AND NOTHERN IRELAND' => 'GB',
            'GERMANY' => 'DE',
            'FRANCE' => 'FR',
            'CANADA' => 'CA',
            'AUSTRALIA' => 'AU',
            'ISRAEL' => 'IL',
            'SPAIN' => 'ES',
            'ITALY' => 'IT',
            'NETHERLANDS' => 'NL',
            'BELGIUM' => 'BE',
            'SWITZERLAND' => 'CH',
            'AUSTRIA' => 'AT',
            'SWEDEN' => 'SE',
            'NORWAY' => 'NO',
            'DENMARK' => 'DK',
            'FINLAND' => 'FI',
            'IRELAND' => 'IE',
            'PORTUGAL' => 'PT',
            'POLAND' => 'PL',
            'CZECH REPUBLIC' => 'CZ',
            'GREECE' => 'GR',
            'ROMANIA' => 'RO',
            'HUNGARY' => 'HU',
            'RUSSIA' => 'RU',
            'UKRAINE' => 'UA',
            'TURKEY' => 'TR',
            'NEW ZEALAND' => 'NZ',
            'JAPAN' => 'JP',
            'SOUTH KOREA' => 'KR',
            'CHINA' => 'CN',
            'CHINA (PEP REP)' => 'CN',
            'HONG KONG' => 'HK',
            'TAIWAN' => 'TW',
            'SINGAPORE' => 'SG',
            'MALAYSIA' => 'MY',
            'THAILAND' => 'TH',
            'INDONESIA' => 'ID',
            'PHILIPPINES' => 'PH',
            'VIETNAM' => 'VN',
            'BRAZIL' => 'BR',
            'INDIA' => 'IN',
            'PAKISTAN' => 'PK',
            'BANGLADESH' => 'BD',
            'UNITED ARAB EMIRATES' => 'AE',
            'SAUDI ARABIA' => 'SA',
            'QATAR' => 'QA',
            'KUWAIT' => 'KW',
            'BAHRAIN' => 'BH',
            'OMAN' => 'OM',
            'JORDAN' => 'JO',
            'LEBANON' => 'LB',
            'EGYPT' => 'EG',
            'MOROCCO' => 'MA',
            'SOUTH AFRICA' => 'ZA',
            'NIGERIA' => 'NG',
            'KENYA' => 'KE',
            'MEXICO' => 'MX',
            'ARGENTINA' => 'AR',
            'CHILE' => 'CL',
            'COLOMBIA' => 'CO',
            'PERU' => 'PE',
        ],
        'rate_categories' => [
            'US' => 1,
            'USA' => 1,
            'UNITED STATES' => 1,
            'CA' => 4,
            'CANADA' => 4,
            'GB' => 3,
            'UNITED KINGDOM' => 3,
            'GREAT BRITAIN AND NOTHERN IRELAND' => 3,
            'DE' => 3,
            'GERMANY' => 3,
            'FR' => 3,
            'FRANCE' => 3,
            'ES' => 3,
            'SPAIN' => 3,
            'IT' => 3,
            'ITALY' => 3,
            'NL' => 4,
            'NETHERLANDS' => 4,
            'BE' => 3,
            'BELGIUM' => 3,
            'CH' => 3,
            'SWITZERLAND' => 3,
            'AT' => 3,
            'AUSTRIA' => 3,
            'SE' => 13,
            'SWEDEN' => 13,
            'NO' => 13,
            'NORWAY' => 13,
            'DK' => 13,
            'DENMARK' => 13,
            'FI' => 13,
            'FINLAND' => 13,
            'IE' => 3,
            'IRELAND' => 3,
            'PT' => 3,
            'PORTUGAL' => 3,
            'PL' => 3,
            'POLAND' => 3,
            'GR' => 10,
            'GREECE' => 10,
            'HU' => 3,
            'HUNGARY' => 3,
            'RU' => 11,
            'RUSSIA' => 11,
            'UA' => 10,
            'UKRAINE' => 10,
            'TR' => 3,
            'TURKEY' => 3,
            'AU' => 2,
            'AUSTRALIA' => 2,
            'NZ' => 6,
            'NEW ZEALAND' => 6,
            'JP' => 5,
            'JAPAN' => 5,
            'KR' => 5,
            'SOUTH KOREA' => 5,
            'CN' => 5,
            'CHINA' => 5,
            'CHINA (PEP REP)' => 5,
            'HK' => 5,
            'HONG KONG' => 5,
            'TW' => 4,
            'TAIWAN' => 4,
            'SG' => 5,
            'SINGAPORE' => 5,
            'TH' => 5,
            'THAILAND' => 5,
            'ID' => 7,
            'INDONESIA' => 7,
            'VN' => 6,
            'VIETNAM' => 6,
            'IN' => 4,
            'INDIA' => 4,
            'BD' => 4,
            'BANGLADESH' => 4,
            'AE' => 3,
            'UNITED ARAB EMIRATES' => 3,
            'BH' => 3,
            'BAHRAIN' => 3,
            'ZA' => 2,
            'SOUTH AFRICA' => 2,
            'BR' => 6,
            'BRAZIL' => 6,
            'AR' => 6,
            'ARGENTINA' => 6,
        ],
    ],
];
